package dev.snowcave.guilds.core;

/**
 * Created by WinterBear on 22/12/2020.
 */
public enum GuildSymbol {

    DEFAULT("✦"),
    FLOWER("❀"),
    HEART("❤"),
    CROSS("✖"),
    MUSIC("♫"),
    MOON("☽"),
    SUN("☀"),
    SKULL("☠"),
    YINYANG("☯"),
    FLORETTE("❁"),
    SPARKLE("❈"),
    COMPASS("❂"),
    STAR("★"),
    COMET("☄"),
    MUG("☕"),
    MARK("※"),
    BOW("\uD83C\uDFF9"),
    ALIEN("\uD83D\uDC7D"),
    ROBOT("\uD83E\uDD16"),
    INVADER("\uD83D\uDC7E"),
    ARM("\uD83D\uDCAA"),
    ROBOTARM("\uD83E\uDDBE"),
    UMBRELLA("☂"),
    SHADES("\uD83D\uDD76"),
    PACK("\uD83C\uDF92"),
    OWL("\uD83E\uDD89"),
    WHALE("\uD83D\uDC33"),
    DOLPHIN("\uD83D\uDC2C"),
    FISH("🐠"),
    CRAB("\uD83E\uDD80"),
    LOBSTER("\uD83E\uDD9E"),
    OCTOPUS("\uD83D\uDC19"),
    DINOSAUR("\uD83E\uDD95"),
    SNAKE("\uD83D\uDC0D"),
    SPIDER("\uD83D\uDD77"),
    BUTTERFLY("\uD83E\uDD8B"),
    BEE("\uD83D\uDC1D"),
    UNICORN("\uD83E\uDD84"),
    BIRD("\uD83D\uDC26"),
    BUNNY("\uD83D\uDC30"),
    SHELL("\uD83D\uDC1A"),
    LEAF("\uD83C\uDF41"),
    DRAGON("\uD83D\uDC09"),
    PALM_TREE("\uD83C\uDF34"),
    PAWS("\uD83D\uDC3E"),
    CHICKEN("\uD83D\uDC13"),
    CAT("🐈"),
    RHINO("\uD83E\uDD8F"),
    ELEPHANT("\uD83E\uDDA3"),
    FIRE("\uD83D\uDD25"),
    BOLT("⚡"),
    MOON2("\uD83C\uDF1B"),
    CHEESE("\uD83E\uDDC0"),
    PINEAPPLE("\uD83C\uDF4D"),
    LEMON("\uD83C\uDF4B"),
    PIZZA("\uD83C\uDF55"),
    POT("\uD83E\uDED6"),
    CAKE("\uD83C\uDF70"),
    ICECREAM("\uD83C\uDF66"),
    TRAIN("\uD83D\uDE82"),
    GONDOLA("\uD83D\uDEA1"),
    DESERT("\uD83C\uDFDC"),
    MOUNTAIN("⛰"),
    CITADEL("\uD83C\uDFEF"),
    CASTLE("\uD83C\uDFF0"),
    ROCKET("\uD83D\uDE80"),
    SATELLITE("🛰"),
    BOAT("⛵"),
    UFO("🛸"),
    SETTLEMENT("\uD83C\uDFD5"),
    BULB("\uD83D\uDCA1"),
    TV("\uD83D\uDCFA"),
    TOOLS("\uD83D\uDEE0"),
    DIAMOND("💎"),
    SWAG("\uD83D\uDCB0"),
    KEY("\uD83D\uDDDD"),
    BARBER("\uD83D\uDC88"),
    CANDLE("\uD83D\uDD6F"),
    MAGNIFYINGGLASS("\uD83D\uDD0D"),
    BOOK("\uD83D\uDCD6"),
    HEARTRISE("\uD83D\uDC99"),
    HUNDRED("💯"),
    NOTE("\uD83C\uDFB5"),
    BELL("\uD83D\uDD14");

    private final String symbol;

    GuildSymbol(String symbol) {
        this.symbol = symbol;
    }

    public String getSymbol() {
        return symbol;
    }
}
